# Generated by Django 5.0.2 on 2024-02-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('id',), 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={'ordering': ('id',), 'verbose_name': 'UserComment', 'verbose_name_plural': 'UserComments'},
        ),
    ]
